# Uncomment the next line to define a global platform for your project
platform :ios, '11.4'
source 'https://github.com/CocoaPods/Specs.git'
target 'walkfinder' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  #use_frameworks!
    pod 'GoogleMaps'
    pod 'GooglePlaces'

  # Pods for walkfinder

  target 'walkfinderTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'walkfinderUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
